# Generated by Django 4.0.6 on 2022-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('DNI', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('apepat', models.CharField(max_length=80)),
                ('apemat', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
    ]
