# Generated by Django 4.0.6 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
